dist: trusty
os: linux

language: node_js
node_js: 14

addons:
  ssh_known_hosts: expeditiegrensland.nl

before_script:
- npm install -g gulp-cli
- openssl aes-256-cbc -K $encrypted_27d6bcd2b8d4_key -iv $encrypted_27d6bcd2b8d4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

script: gulp build:prod

deploy:
  provider: script
  script: rsync -rp --delete-after $TRAVIS_BUILD_DIR/dist/. nodejs@expeditiegrensland.nl:/var/www/expeditiegrensland.nl/"$TRAVIS_BRANCH"/dist-new/ && ssh nodejs@expeditiegrensland.nl sh /var/www/expeditiegrensland.nl/deploy.sh "$TRAVIS_BRANCH"
  skip_cleanup: true
  on:
    all_branches: true
    condition: $(ssh nodejs@expeditiegrensland.nl sh /var/www/expeditiegrensland.nl/deploy_if.sh "$TRAVIS_BRANCH") == 0
