name: Build & Deploy

on:
- push
- pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Build using gulp.js
      run: gulp build:prod
    - name: Tar distribution folder
      run: tar -cvf Distribution.tar dist
    - name: Upload distribution folder artifact
      uses: actions/upload-artifact@v2
      with:
        name: Distribution-folder
        path: dist
    - name: Upload distribution artifact
      uses: actions/upload-artifact@v2
      with:
        name: Distribution
        path: Distribution.tar

