name: Build & Check

on: push

permissions:
  contents: write

jobs:
  build:
    name: Check & Build
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@expeditie-grensland"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm run lint

      - name: Run build
        run: pnpm run build:prod

      - name: Set pre-release version
        if: github.ref == 'refs/heads/master'
        run: npm version --git-tag-version false prerelease --preid "pre.$(date +"%Y%m%d").$(git rev-parse --short=8 HEAD)"

      - name: Publish pre-release
        if: github.ref == 'refs/heads/master'
        run: npm publish -ddd --tag next --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
