name: Build & Deploy

on: push

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Check, Build & Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@expeditie-grensland"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run checks
        run: pnpm run lint

      - name: Run build
        run: pnpm run build:prod

      - name: Set pre-release version
        if: github.ref == 'refs/heads/master'
        run: pnpm version --git-tag-version false "$(pnpm version --git-tag-version false patch)-pre.$(date +"%Y%m%d").$(git rev-parse --short=8 HEAD)"

      - name: Publish pre-release
        if: github.ref == 'refs/heads/master'
        run: pnpm publish --tag next --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-latest:
    name: Deploy Latest
    runs-on: ubuntu-22.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
    environment:
      name: latest
      url: https://expeditiegrensland.nl
      
    steps:
      - name: Install SSH configuration
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_SSH_HOSTS }}

      - name: Deploy to server
        run: ssh -T ${{ secrets.DEPLOY_SERVER }}

  deploy-next:
    name: Deploy Next
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/master'
    environment:
      name: next
      url: https://next.expeditiegrensland.nl
      
    steps:
      - name: Install SSH configuration
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.DEPLOY_SSH_HOSTS }}

      - name: Deploy to server
        run: ssh -T ${{ secrets.DEPLOY_SERVER }}
