name: Build & Check

on: push

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build using gulp.js
        run: gulp build:prod

      - name: Create package
        id: npm_pack
        run: echo "package_name=$(npm pack)" >> $GITHUB_OUTPUT

      - name: Rename package
        run: mv "${{ steps.npm_pack.outputs.package_name }}" expeditiegrensland-website.tar.gz

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: expeditiegrensland-website.tar.gz

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  deploy_production:
    name: Deploy to production
    if: github.ref == 'refs/heads/release'
    needs:
      - build
      - check
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      environment_url: https://expeditiegrensland.nl
      prerelease: false
    secrets: inherit

  deploy_staging:
    name: Deploy to staging
    if: github.ref == 'refs/heads/master'
    needs:
      - build
      - check
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      environment_url: https://staging.expeditiegrensland.nl
      prerelease: true
    secrets: inherit
