name: Build & Deploy

on:
- push

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Build using gulp.js
      run: gulp build:prod
    - name: Upload distribution artifact
      uses: actions/upload-artifact@v2
      with:
        name: Distribution
        path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: deploy-release
    steps:
    - name: Download distribution artifact
      uses: actions/download-artifact@v2
      with:
        name: Distribution
        path: dist
    - name: Install SSH configuration
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      config: ${{ secrets.SSH_CONFIG }}
    - name: Upload deployment
      run: rsync -rp dist/. ${{ secrets.DEPLOYMENT_SERVER }}:${{ secrets.DEPLOYMENT_FOLDER }}
    - name: Run deployment
      run: ssh ${{ secrets.DEPLOYMENT_SERVER }} ${{ secrets.DEPLOYMENT_COMMAND }}
