name: Build

on: push

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build using gulp.js
        run: gulp build:prod

      - name: Release & Deploy
        uses: ./.github/workflows/deploy.yml
        if: github.env == 'refs/heads/release'
        with:
          secrets: inherit
