name: Release Version

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

permissions:
  contents: write

jobs:
  release-version:
    name: Release Version
    runs-on: ubuntu-22.04
    if: github.ref_name == 'master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update version
        run: npm version $TYPE
        env:
          TYPE: ${{ inputs.releaseType }}

      - name: Push changes & tag
        run: git push --followTags
